#!/bin/bash
# read the name of the user and print hello

echo "Hello! What is your name"
read name
echo "Welcome, $name"

# single quotes prevent the expansion of the variable
echo 'Your name was stored in $name'

# exercise: write a script that asks the user for a 
# filename and create an empty file named after it

echo "$name, type in a name for a new file"
read filename
echo "Thank you. Creating a file named $filename"
touch $filename.txt
echo "File $filename created."

echo "$name, what flavor of icecream do you like, chocolate or vanilla?"
read flavor
if [ "$flavor" = "chocolate" ]; then
    echo "Here is a virtual chocolate ice cream cone! <3"
else
    echo "Sorry, I don't rock with vanilla. Game Over."
fi
