#!/bin/bash
# read the name of the user and print hello

echo "Hello! What is your name"
read name
echo "Welcome, $name"

# single quotes prevent the expansion of the variable
echo 'Your name was stored in $name'

# exercise: write a script that asks the user for a 
# filename and create an empty file named after it

echo "$name, type in a name for a new file"
read filename
echo "Thank you. Creating a file named $filename"
touch $filename.txt
echo 'File $filename created.'
